
export const GET_TODO_LIST_REQUEST="GET_TODO_LIST_REQUEST";
export const GET_TODO_LIST_SUCCESS="GET_TODO_LIST_SUCCESS";
export const GET_TODO_LIST_FAILURE="GET_TODO_LIST_FAILURE";


export const ADD_TODO_REQUEST="ADD_TODO_REQUEST";
export const ADD_TODO_SUCCESS="ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE="ADD_TODO_FAILURE";

export const TOGGLE_TODO_REQUEST="TOGGLE_TODO_REQUEST";
export const TOGGLE_TODO_SUCCESS="TOGGLE_TODO_SUCCESS";
export const TOGGLE_TODO_FAILURE="TOGGLE_TODO_FAILURE";


export const DELETE_TODO_REQUEST="DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILURE="DELETE_TODO_FAILURE";


export const UPDATE_TODO_REQUEST="UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS="UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAILURE="UPDATE_TODO_FAILURE";

